Repository CivMC/CivModCore, pull requests merged in 2023-12, with the labels that each got.

#89 Use the proper disablePlugin API
  paper/src/main/java/vg/civcraft/mc/civmodcore/ACivMod.java
Labels: Category: Technical Debt, Priority: Medium

#93 Remove MapColours
  paper/src/main/java/vg/civcraft/mc/civmodcore/CivModCorePlugin.java
  paper/src/main/java/vg/civcraft/mc/civmodcore/maps/MapColours.java
Labels: Category: Technical Debt, Priority: Low

#97 Remove ParticleEffect
  paper/src/main/java/vg/civcraft/mc/civmodcore/particles/ParticleEffect.java
Labels: Category: Technical Debt, Priority: Low

#88 Remove ACivMod.getInstance(Some.class)
  paper/src/main/java/vg/civcraft/mc/civmodcore/ACivMod.java
Labels: Category: Technical Debt, Priority: Medium

#91 Use reusable workflows
  .github/workflows/build.yml
  .github/workflows/comment-on-pr.yaml
  .github/workflows/publish.yml
  build.gradle.kts
  settings.gradle.kts
Labels: Category: Feature, Priority: Medium

#100 Implement reusable workflows
  .github/workflows/build.yml
  .github/workflows/comment-on-pr.yaml
  .github/workflows/pr_updated.yml
  .github/workflows/pr_updated_completed.yml
  .github/workflows/publish.yml
  .github/workflows/tag_created.yml
  build.gradle.kts
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  paper/build.gradle.kts
  settings.gradle.kts
Labels: Category: Technical Debt, Priority: High
